###############################################
# Node identity
###############################################
CONFIG_APP_NODE_ID="12"

###############################################
# Measurement cadence
###############################################
CONFIG_APP_MEASUREMENT_PERIOD_S=60

###############################################
# Thread role
###############################################
CONFIG_OPENTHREAD_MTD=y
CONFIG_OPENTHREAD_FTD=n
CONFIG_OPENTHREAD_JOINER=y

###############################################
# Features
###############################################
CONFIG_APP_PUBLISH_UPTIME=y
CONFIG_APP_DEBUG_SENSOR=y

###############################################
# Sensors enabled
###############################################
CONFIG_APP_USE_SHT41_SENSOR=y
CONFIG_APP_USE_SCD41_SENSOR=n

###############################################
# Drivers required by sensors
###############################################
CONFIG_SHT4X=y