# -------------------------------------------------
# Device Type: MTD Sleepy End Device (SED)
# -------------------------------------------------
CONFIG_OPENTHREAD_MTD=y
CONFIG_OPENTHREAD_MAX_IP_ADDR_PER_CHILD=6
CONFIG_OPENTHREAD_THREAD_STACK_SIZE=9216
CONFIG_OPENTHREAD_MTD_SED=y
CONFIG_OPENTHREAD_POLL_PERIOD=60000