CONFIG_OPENTHREAD_THREAD_VERSION_1_4=y
CONFIG_NET_L2_IEEE802154=n


CONFIG_OPENTHREAD_RADIO_LINK_IEEE_802_15_4_ENABLE=y

# --- unblock Kconfig warnings op nRF54L15 ---
CONFIG_NRF_802154_TEMPERATURE_UPDATE=n



